TEMPLATE = subdirs

# Product information
VERSION = 0.1.0
QMAKE_TARGET_COMPANY = ""
QMAKE_TARGET_PRODUCT = ""
QMAKE_TARGET_DESCRIPTION = ""
QMAKE_TARGET_COPYRIGHT = "Copyrights(c) 2013"

SUBDIRS = src
