#############################################################################
# Makefile for building: ../bin/test.app/Contents/MacOS/test
# Generated by qmake (2.01a) (Qt 4.8.4) on: ?? 2? 15 18:34:53 2013
# Project:  test.pro
# Template: app
# Command: /Developer/Tools/Qt/qmake -o test.xcodeproj/project.pbxproj test.pro
#############################################################################

MOC       = /Developer/Tools/Qt/moc
UIC       = /Developer/Tools/Qt/uic
LEX       = flex
LEXFLAGS  = 
YACC      = yacc
YACCFLAGS = -d
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
INCPATH       = -I/usr/local/Qt4.8/mkspecs/macx-xcode -I. -I/Library/Frameworks/QtCore.framework/Versions/4/Headers -I/usr/include/QtCore -I/Library/Frameworks/QtGui.framework/Versions/4/Headers -I/usr/include/QtGui -I/usr/include -I. -I.build -Iparser -Iparser/record -Isymbol -I.build -I/usr/local/include -I/System/Library/Frameworks/CarbonCore.framework/Headers -F/Library/Frameworks
DEL_FILE  = rm -f
MOVE      = mv -f

IMAGES = 
PARSERS =
preprocess: $(PARSERS) compilers
clean preprocess_clean: parser_clean compiler_clean

parser_clean:
check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compilers: .build/db.lex.cpp .build/db.tab.cpp .build/db.tab.h .build/moc_testviewwidget.cpp
compiler_flex_make_all: .build/db.lex.cpp
compiler_flex_clean:
	-$(DEL_FILE) .build/db.lex.cpp
.build/db.lex.cpp: parser/db.l \
		.build/db.tab.h
	flex -o.build/db.lex.cpp parser/db.l

compiler_bison_make_all: .build/db.tab.cpp
compiler_bison_clean:
	-$(DEL_FILE) .build/db.tab.cpp .build/db.tab.h .build/db.output
.build/db.tab.cpp: parser/db.y
	bison -t -v parser/db.y -o .build/db.tab.cpp --defines=.build/db.tab.h

compiler_bisonheader_make_all: .build/db.tab.h
compiler_bisonheader_clean:
	-$(DEL_FILE) .build/db.tab.h
.build/db.tab.h: parser/db.y \
		.build/db.tab.cpp
	@true

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: .build/moc_testviewwidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) .build/moc_testviewwidget.cpp
.build/moc_testviewwidget.cpp: tests/testviewwidget.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ tests/testviewwidget.h -o .build/moc_testviewwidget.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: .build/qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) .build/qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_flex_clean compiler_bison_clean compiler_bisonheader_clean compiler_moc_header_clean 

